apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-client-validator
  namespace: onap
  labels:
    app: helm-client-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-client-validator
  template:
    metadata:
      labels:
        app: helm-client-validator
    spec:
      containers:
        - name: helm-client-validator
          imagePullPolicy: IfNotPresent
          image: onap-dev-local.esisoj70.emea.nsn-net.net/towrobel/helm-client-validator:1.5.0
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: helm-client-validator-service
  namespace: onap
  labels:
    app: helm-client-validator
spec:
  selector:
    app: helm-client-validator
  type: NodePort
  ports:
    - port: 8244
      targetPort: 8080
      nodePort: 32244
